import './globals.css';
import TanstackQueryProvider from '@/api/provider';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import theme from '@/theme';
import { Toaster } from 'sonner';
import HighlightOffOutlinedIcon from '@mui/icons-material/HighlightOffOutlined';
import CheckCircleOutlineOutlinedIcon from '@mui/icons-material/CheckCircleOutlineOutlined';
import InfoOutlinedIcon from '@mui/icons-material/InfoOutlined';
import WarningOutlinedIcon from '@mui/icons-material/WarningOutlined';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
    return (
        <html lang='en'>
            <body>
                <AppRouterCacheProvider>
                    <TanstackQueryProvider>
                        <Toaster
                            duration={5000}
                            position='top-center'
                            pauseWhenPageIsHidden
                            icons={{
                                error: <HighlightOffOutlinedIcon />,
                                success: <CheckCircleOutlineOutlinedIcon />,
                                info: <InfoOutlinedIcon />,
                                warning: <WarningOutlinedIcon />,
                            }}
                        />
                        <ThemeProvider theme={theme}>{children}</ThemeProvider>
                    </TanstackQueryProvider>
                </AppRouterCacheProvider>
            </body>
        </html>
    );
}
